# Generated by Django 2.1.8 on 2019-05-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='Task Name')),
                ('task_description', models.TextField(verbose_name='Task Description')),
                ('task_due_date', models.DateField(verbose_name='Task Deadline')),
                ('task_time', models.DurationField(verbose_name='Task Duration')),
                ('task_ended', models.BooleanField(verbose_name='Is Done ?')),
            ],
        ),
    ]
