# Generated by Django 2.1.8 on 2019-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(default='Ajouter une description', verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_ended',
            field=models.BooleanField(default=False, verbose_name='Is Done ?'),
        ),
    ]
