# Generated by Django 2.1.8 on 2019-05-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190516_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='my_tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolist.Task'),
        ),
    ]
