# Generated by Django 2.1.8 on 2019-05-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20190516_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='my_tasks',
            field=models.ManyToManyField(to='todolist.Task'),
        ),
    ]
