# Generated by Django 2.1.8 on 2019-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_remove_tasklist_my_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='my_tasks',
            field=models.ManyToManyField(to='todolist.Task'),
        ),
    ]
