# Generated by Django 2.1.8 on 2019-05-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_tasklist_my_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='my_tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='todolist.TaskList'),
        ),
    ]
