# Generated by Django 2.1.8 on 2019-05-17 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0009_auto_20190516_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='list_users',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='list_users',
            field=models.ManyToManyField(related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
